apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s
  labels:
    name: springboot-k8s
    app: springboot-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-k8s
  template:
    metadata:
      name: springboot-k8s
      labels:
        app: springboot-k8s
        name: springboot-k8s
    spec:
      restartPolicy: Always
      containers:
        - name: springboot-k8s
          image: bbvss/springboot-k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
---

apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s
  labels:
    app: springboot-k8s
    name: springboot-k8s
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30080
  selector:
    app: springboot-k8s
    name: springboot-k8s